smbrewing/blog/models.py
# -*- coding: utf-8 -*-
"""Beer models."""
import datetime as dt
import pytz
import enum
import re

from smbrewing.database import Column, Model, SurrogatePK, db, reference_col, relationship

from sqlalchemy import event
from flask import current_app
from flask_restful import fields

class Post(SurrogatePK, Model):
    """Model for blog posts

    """

    __tablename__ = 'blog_posts'
    timestamp = Column(db.DateTime, default=dt.datetime.utcnow)
    content = Column(db.Text, nullable=False)
    published = Column(db.Boolean, default=True)
    title = Column(db.String(140), nullable=False)
    slug = Column(db.String(140))
    user_id = reference_col('users')
    user = relationship('User', backref='blog_posts')

    def save(self, *args, **kwargs):
        if not self.slug:
            current_app.logger.debug("Detected a blog post without a slug - generating")
            self.slug = re.sub('[^\w]+', '-', self.title.lower())
            current_app.logger.debug("Post slug: " + self.slug)

        # update TZ INFO
        # naive_obj = self.timestamp
        # localtz = pytz.timezone("US/Eastern")
        # local_dt = localtz.localize(naive_obj)
        # self.timestamp = local_dt

        return super(Post, self).save()

    def __init__(self, content='', title='', **kwargs):
        db.Model.__init__(self, content=content, title=title, **kwargs)

    def __repr__(self):
        return '<Blog post {0}>'.format(self.id)

    def __unicode__(self):
        return 'BlogPost: {0}'.format(self.title)

    def getMonth(self):
        return self.timestamp.strftime('%B')

    def getLocalTimestamp(self, tz='America/New_York'):
        dt_obj = self.timestamp
        localtz = pytz.timezone(tz)
        return localtz.localize(dt_obj)

class Category(SurrogatePK, Model):
    """Blog post categories

    """

    __tablename__ = 'blog_categories'
    name = Column(db.String(64), nullable=False)

    def __init__(self, name='', **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Category {0}>'.format(self.name)

    def __unicode__(self):
        return '{0}'.format(self.name)

smbrewing/blog/__init__.py
# -*- coding: utf-8 -*-
"""The blogging module"""
from . import views

smbrewing/blog/views.py
# -*- coding: utf-8 -*-
"""Blog views."""
from flask import Blueprint, render_template, current_app, flash, redirect, url_for, request
from flask_login import login_required, current_user

from .models import Post, Category

from smbrewing.utils import flash_errors

blueprint = Blueprint('blog', __name__, url_prefix='/blog', static_folder='../static')

@blueprint.app_template_filter()
def monthText(month):
    months = {
        1: 'January',
        2: 'February',
        3: 'March',
        4: 'April',
        5: 'May',
        6: 'June',
        7: 'July',
        8: 'August',
        9: 'September',
        10: 'October',
        11: 'November',
        12: 'December'
    }
    return months[month]

def get_post_archive():

    # TODO - any time get_post_archive is returned with a template, it's a second
    # db query. Might try to find a better way to do this
    ym_list = [(p.timestamp.year, p.timestamp.month) for p in Post.query.all()]
    date_list = {}
    for ym in ym_list:
        if not date_list.has_key(ym[0]): # check for year
            date_list[ym[0]] = {} #init empty list for that year

        if not date_list[ym[0]].has_key(ym[1]):
            date_list[ym[0]][ym[1]] = 0

        date_list[ym[0]][ym[1]] += 1

    return date_list

@blueprint.route('/')
def index():

    posts = Post.query.filter(Post.published == True).all()
    current_app.logger.debug("Found {0} blog posts in the database".format(len(posts)))

    return render_template('blog/index.html', posts=posts, blog_history=get_post_archive())

@blueprint.route('/<string:slug>')
def blogPost(slug):

    post = Post.query.filter(Post.slug == slug).first()

    return render_template('blog/post.html', post=post, blog_history=get_post_archive())

@blueprint.route('/archive')
def blogArchives():
    pass

@blueprint.route('/archive/<int:year>/<int:month>')
def archiveMonth(year, month):

    posts = Post.query.all()
    archivePosts = []
    for p in posts:
        if p.timestamp.year == year and p.timestamp.month == month:
            archivePosts.append(p)

    return render_template('blog/archiveMonth.html', posts=archivePosts,
                           blog_history=get_post_archive(), year=year,
                           month=month)

smbrewing/templates/blog/archiveMonth.html
{% extends "layout.html" %}

{% block css %}
{% endblock %}

{% block header %}
<div class="page-header">
    <h1>Sunday Morning Brewing Blog   <small>{{ month|monthText() }} {{ year }}</small></h1>
</div>
{% endblock %}

{% block content %}
<div class="col-md-9">
{% for post in posts|sort(attribute='timestamp',reverse=True) %}
<div class="row">
    <h3>
        <a href="{{ url_for('blog.blogPost', slug=post.slug) }}">{{ post.title }}</a>
    </h3>
    <p>Created on {{ post.timestamp.strftime('%m/%d/%y at %I:%M%p') }} by {{ post.user }}</p>
    <p>{{ post.content }}</p>
</div>
{% endfor %}
</div>

<div class="col-md-3">
<h4>Blog History</h4>
<ul class="list-group">
    {% for year in blog_history|sort(reverse=True) %}
    <li class="list-group-item">
        {{ year }}
        <ul>
            {% for month in blog_history[year].keys()|sort() %}
            <li>
                <span class="badge pull-right">{{ blog_history[year][month] }}</span>
                <a href="{{ url_for('blog.archiveMonth', month=month, year=year) }}">{{ month|monthText() }}</a>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
</div>
{% endblock %}

{% block js %}
{% endblock %}

smbrewing/templates/blog/index.html
{% extends "layout.html" %}

{% block css %}
{% endblock %}

{% block header %}
<div class="page-header">
    <h1>Sunday Morning Brewing Blog</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-md-9">
{% for post in posts|sort(attribute='timestamp',reverse=True) %}
<div class="row">
    <h3>
        <a href="{{ url_for('blog.blogPost', slug=post.slug) }}">{{ post.title }}</a>
    </h3>
    <p>Created on {{ post.timestamp.strftime('%m/%d/%y at %I:%M%p') }} by {{ post.user }}</p>
    <p>{{ post.content }}</p>
</div>
{% endfor %}
</div>

<div class="col-md-3">
<h4>Blog History</h4>
<ul class="list-group">
    {% for year in blog_history|sort(reverse=True) %}
    <li class="list-group-item">
        {{ year }}
        <ul>
            {% for month in blog_history[year].keys()|sort() %}
            <li>
                <span class="badge pull-right">{{ blog_history[year][month] }}</span>
                <a href="{{ url_for('blog.archiveMonth', month=month, year=year) }}">{{ month|monthText() }}</a>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
</div>
{% endblock %}

{% block js %}
{% endblock %}

smbrewing/templates/blog/post.html
{% extends "layout.html" %}

{% block css %}
{% endblock %}

{% block header %}
<div class="page-header">
    <h1>Sunday Morning Brewing Blog</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-md-9">
<div class="row">
    <h3>{{ post.title }}</h3>
    <p>Created on {{ post.timestamp.strftime('%m/%d/%y at %I:%M%p') }} by {{ post.user }}</p>
    <p>{{ post.content }}</p>
</div>
</div>

<div class="col-md-3">
<h4>Blog History</h4>
<ul class="list-group">
    {% for year in blog_history|sort(reverse=True) %}
    <li class="list-group-item">
        {{ year }}
        <ul>
            {% for month in blog_history[year].keys()|sort() %}
            <li>
                <span class="badge pull-right">{{ blog_history[year][month] }}</span>
                <a href="{{ url_for('blog.archiveMonth', month=month, year=year) }}">{{ month|monthText() }}</a>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
</div>
{% endblock %}

{% block js %}
{% endblock %}