smbrewing/beers/views.py
# -*- coding: utf-8 -*-
"""Beer views."""
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, current_app
from flask_login import current_user

from .models import Beer

from functools import wraps
import json

blueprint = Blueprint('beers', __name__, url_prefix='/beers', static_folder='../static')

# @blueprint.app_template_filter()
# def splitSteps(recipe):
#     steps_json = recipe.steps
#     return [s for s in steps_json['steps']]

# def login_required(role="ANY"):
#     def wrapper(fn):
#         @wraps(fn)
#         def decorated_view(*args, **kwargs):
#             if not current_user.is_authenticated:
#                 return user_unauthorized
#             user_roles = [r.name for r in current_user.roles]
#             # print "DEBUG: Checking that {0} has the {1} role".format(
#             #     current_user.username,
#             #     role
#             # )
#             if ((role not in user_roles) and (role != "ANY")):
#                 return user_unauthorized
#             return fn(*args, **kwargs)
#         return decorated_view
#     return wrapper

@blueprint.route('/')
def index():
    """Render the beer overview page"""
    beers = Beer.query.all()

    return render_template('beers/beers.html', beers=beers)

# @blueprint.route('/brewday')
# # @login_required(role="brewer")
# def brewday():
#
#     recipes = BeerRecipe.query.all()
#
#     # check session for recipe from previous page visit
#     if session.get('receipe_id'):
#         current_app.logger.debug("Found receipe in session, loading recipe with page")
#         recipe_id = session.get('receipe_id')
#         return render_template('beers/brewday.html', recipes=recipes, recipe_id=receipe_id)
#
#     return render_template('beers/brewday.html', recipes=recipes)
#
#
#
# @blueprint.route('/newrecipe', methods = ['GET'])
# # @login_required(role="brewer")
# def newrecipe():
#     """Route for creating a new recipe from the front endpoint
#
#     """
#
#     yeasts = Yeast.query.all()
#     hops = Hop.query.all()
#     fermentables = Fermentable.query.all()
#     additives = Additive.query.all()
#     load_session_recipe = 'false'
#
#     if session.get('draft_recipe'):
#         load_session_recipe = 'true'
#
#     return render_template('beers/newrecipe.html', yeasts=yeasts,
#                                                    hops=hops,
#                                                    fermentables=fermentables,
#                                                    additives=additives,
#                                                    load_session_recipe=load_session_recipe)
#
# @blueprint.route('/newrecipe/pdf')
# def getRecipePDF():
#
#     return render_pdf(url_for('beers.newrecipe'))
#
# @blueprint.route('/managebrewery')
# # @login_required(role="brewer")
# def manageBrewery():
#
#     fermenters = Vessel.query.filter((Vessel.vessel_type == 'carboy') | (Vessel.vessel_type == 'bucket')).all()
#
#
#     return render_template('beers/managebrewery.html', fermenters=fermenters)

smbrewing/blog/views.py
# -*- coding: utf-8 -*-
"""Blog views."""
from flask import Blueprint, render_template, current_app, flash, redirect, url_for, request
from flask_login import login_required, current_user

from .models import Post, Category

from smbrewing.utils import flash_errors

blueprint = Blueprint('blog', __name__, url_prefix='/blog', static_folder='../static')

@blueprint.app_template_filter()
def monthText(month):
    months = {
        1: 'January',
        2: 'February',
        3: 'March',
        4: 'April',
        5: 'May',
        6: 'June',
        7: 'July',
        8: 'August',
        9: 'September',
        10: 'October',
        11: 'November',
        12: 'December'
    }
    return months[month]

def get_post_archive():

    # TODO - any time get_post_archive is returned with a template, it's a second
    # db query. Might try to find a better way to do this
    ym_list = [(p.timestamp.year, p.timestamp.month) for p in Post.query.all()]
    date_list = {}
    for ym in ym_list:
        if not date_list.has_key(ym[0]): # check for year
            date_list[ym[0]] = {} #init empty list for that year

        if not date_list[ym[0]].has_key(ym[1]):
            date_list[ym[0]][ym[1]] = 0

        date_list[ym[0]][ym[1]] += 1

    return date_list

@blueprint.route('/')
def index():

    posts = Post.query.filter(Post.published == True).all()
    current_app.logger.debug("Found {0} blog posts in the database".format(len(posts)))

    return render_template('blog/index.html', posts=posts, blog_history=get_post_archive())

@blueprint.route('/<string:slug>')
def blogPost(slug):

    post = Post.query.filter(Post.slug == slug).first()

    return render_template('blog/post.html', post=post, blog_history=get_post_archive())

@blueprint.route('/archive')
def blogArchives():
    pass

@blueprint.route('/archive/<int:year>/<int:month>')
def archiveMonth(year, month):

    posts = Post.query.all()
    archivePosts = []
    for p in posts:
        if p.timestamp.year == year and p.timestamp.month == month:
            archivePosts.append(p)

    return render_template('blog/archiveMonth.html', posts=archivePosts,
                           blog_history=get_post_archive(), year=year,
                           month=month)

smbrewing/mgmt/views.py
# -*- coding: utf-8 -*-
"""Mgmt views."""
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, current_app
from flask_login import current_user

from smbrewing.user.models import User
from smbrewing.blog.models import Post, Category
from .models import *

blueprint = Blueprint('mgmt', __name__, static_folder='./static',
                      subdomain='mgmt',
                      template_folder='templates')

@blueprint.route('/')
def index():

    users = [u for u in User.query.all()]
    return render_template('mgmt_index.html', users=users)

@blueprint.route('/blog/archive')
def blog_archive():
    current_app.logger.debug("Loading blog archive")
    posts = Post.query.all()
    categories = Category.query.all()

    return render_template('mgmt_blog_archive.html', posts=posts, categories=categories)

@blueprint.route('/blog/new')
def new_post():

    return render_template('mgmt_create_post.html')

@blueprint.route('/calendar')
def calendar():

    return render_template('mgmt_calendar.html')

@blueprint.route('/minutes')
def minutes():

    meetings = Meeting.query.all()
    return render_template('mgmt_minutes.html', meetings=meetings)

smbrewing/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

smbrewing/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

smbrewing/templates/footer.html
<footer>
    <small>
        <ul class="company">
            <li>© Sunday Morning Brewing, Raleigh, NC</li>
        </ul>

        <ul class="footer-nav">
            {% if current_user and current_user.is_admin %}
            <li><a href="{{ url_for('mgmt.index') }}">Management</a></li>
            <li>
                <a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
            </li>
            <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>
            {% else %}
            <li><a href="{{ url_for('public.login') }}">Admin Login</a></li>
            {% endif %}
            <li><a href="{{ url_for('public.about') }}">About</a></li>
            <li><a href="mailto:contact@smbrewing.local">Contact Us</a></li>
        </ul>
    </small>
</footer>

smbrewing/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    Sunday Morning Brewing

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}
  <style>
  .navbar .navbar-inner {
      padding: 0;
  }

  .navbar .nav {
      margin: 0;
      display: table;
      width: 100%;
  }

  .navbar .nav li {
      display: table-cell;
      width: auto;
      float: none;
  }

  .navbar .nav li a {
      font-weight: bold;
      text-align: center;

  }
  #smb-brand {
      font-size: 24px;
      
  }
  </style>

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<div class="{% block content_class %}container-fluid{% endblock content_class %}">
{% block header %}{% endblock %}
  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

smbrewing/templates/nav.html
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav nav-justified">
                <li><a href="{{ url_for('public.about') }}">Who We Are</a></li>
                <li><a href="{{ url_for('blog.index') }}">Blog</a></li>
                <li>
                    <a class="" href="{{ url_for('public.home') }}" id="smb-brand">
                        <i class="fa fa-beer"></i> <span>SMB </span>
                    </a>
                </li>
                <li><a href="{{ url_for('beers.index') }}">Our Beers</a></li>
                <li><a href="">Events</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>