smbrewing/mgmt/models.py
# -*- coding: utf-8 -*-
"""Management models."""
import datetime as dt
import enum

from flask import current_app
from flask_login import UserMixin
from flask_restful import fields

from sqlalchemy import event
from smbrewing.database import Column, Model, SurrogatePK, db, reference_col, relationship

class Meeting(SurrogatePK, Model):
    """Model for tracking meetings among staff

    """

    __tablename__ = 'meetings'
    date = Column(db.Date, nullable=False, default=dt.datetime.utcnow)
    location = Column(db.String(128))

    def __init__(self, date=None, **kwargs):
        db.Model.__init__(self, date=date, **kwargs)

    def __repr__(self):
        return '<Meeting on {0}>'.format(self.date)

    def __unicode__(self):
        return '{0} Meeting'.format(self.date.strftime('%m/%d/%Y'))


class MeetingNote(SurrogatePK, Model):
    """Model for tracking meeting notes

    """

    __tablename__ = 'meetingnotes'
    date = Column(db.Date, nullable=False, default=dt.datetime.utcnow)
    user_id = reference_col('users')
    user = relationship('User', backref='meetingnotes')
    meeting_id = reference_col('meetings', nullable=False)
    meeting = relationship('Meeting', backref='notes')
    text = Column(db.Text, nullable=False)

    def __init__(self, date=None, meeting_id=None,
                 text='', **kwargs):
        db.Model.__init__(self, date=date, meeting_id=meeting_id,
                          text=text, **kwargs)

    def __repr__(self):
        return '<Note {0} for meeting {1}>'.format(self.id, self.meeting_id)

    def __unicode__(self):
        return 'Note for meeting {0}'.format(self.meeting_id)

class GoalStatusEnum(enum.Enum):
    not_started = "Not Started"
    in_progress = "In Progress"
    finished = "Finished"
    rejected = "Rejected"

class MeetingGoal(SurrogatePK, Model):
    """Model for tracking goals from each meeting

    """

    __tablename__ = 'meetinggoals'
    status = Column(db.Enum(GoalStatusEnum), default=GoalStatusEnum.not_started)
    done = Column(db.Boolean, default=False)
    description = Column(db.Text)
    finished_notes = Column(db.Text)
    meeting_id = reference_col('meetings')
    meeting = relationship('Meeting', backref='goals')
    user_id = reference_col('users')
    assigned_to = relationship('User', backref='goals')
    created_on = Column(db.Date, default=dt.datetime.utcnow)
    due_date = Column(db.Date)
    finished_on = Column(db.Date)

    def __init__(self, status=None, done=False, description='',
                 finished_notes='', **kwargs):
        db.Model.__init__(self, status=status, done=done, description=description,
                          finished_notes=finished_notes, **kwargs)

    def __repr__(self):
        return '<Goal from meeting {0}>'.format(self.meeting_id)

    def __unicode__(self):
        return 'Goal {0} for {1} from meeting {2}'.format(self.id, self.assigned_to, self.meeting_id)

    @staticmethod
    def __json__():
        _json = {
            'id': fields.Integer,
            'status': fields.String,
            'done': fields.Boolean,
            'description': fields.String,
            'meeting_id': fields.Integer,
            'assigned_to': fields.String
        }

        return _json

    def markGoalFinished(self):
        # current_app.logger.debug("Marking goal as finished..")
        self.done = True
        self.finished_on = dt.datetime.utcnow().strftime('%Y-%m-%d')
        # current_app.logger.debug("Done={0} and finished_on={1}".format(self.done, self.finished_on))
        super(MeetingGoal, self).save()
        # current_app.logger.debug("Done={0} and finished_on={1}".format(self.done, self.finished_on))
        return True

    def markGoalUnfinished(self):
        self.done = False
        self.finished_on = None
        return True

class MeetingAttendee(SurrogatePK, Model):
    """Model for tracking who attended what meeting
    """

    __tablename__ = 'meetingattendees'
    user_id = reference_col('users', nullable=False)
    user = relationship('User', backref='meetings_attended')
    meeting_id = reference_col('meetings', nullable=False)
    meeting = relationship('Meeting', backref='attendees')

    def __init__(self, user_id=None, meeting_id=None, **kwargs):
        db.Model.__init__(self, user_id=user_id, meeting_id=meeting_id, **kwargs)

    def __repr__(self):
        return '<User {0} at meeting {1}>'.format(self.user, self.meeting)

    def __unicode__(self):
        return 'User {0} at meeting {1}'.format(self.user, self.meeting)

smbrewing/mgmt/__init__.py
from . import views

smbrewing/mgmt/views.py
# -*- coding: utf-8 -*-
"""Mgmt views."""
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, current_app
from flask_login import current_user

from smbrewing.user.models import User
from smbrewing.blog.models import Post, Category
from .models import *

blueprint = Blueprint('mgmt', __name__, static_folder='./static',
                      subdomain='mgmt',
                      template_folder='templates')

@blueprint.route('/')
def index():

    users = [u for u in User.query.all()]
    return render_template('mgmt_index.html', users=users)

@blueprint.route('/blog/archive')
def blog_archive():
    current_app.logger.debug("Loading blog archive")
    posts = Post.query.all()
    categories = Category.query.all()

    return render_template('mgmt_blog_archive.html', posts=posts, categories=categories)

@blueprint.route('/blog/new')
def new_post():

    return render_template('mgmt_create_post.html')

@blueprint.route('/calendar')
def calendar():

    return render_template('mgmt_calendar.html')

@blueprint.route('/minutes')
def minutes():

    meetings = Meeting.query.all()
    return render_template('mgmt_minutes.html', meetings=meetings)

smbrewing/mgmt/templates/admin_create.html
{% extends 'mgmt_layout.html' %}
{% import 'admin/lib.html' as lib with context %}
{% from 'admin/lib.html' import extra with context %} {# backward compatible #}

{% block css %}
{{ lib.form_css() }}
{% endblock %}

{% block sidebar %}
{% include "admin_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2 id="brand">Create {{ admin_view.name|capitalize }}</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>

                    <form action="{{ action or '' }}" method="POST" role="form" class="form-horizontal form-label-left">
                        {% if form.hidden_tag is defined %}
                            {{ form.hidden_tag() }}
                        {% else %}
                            {% if csrf_token %}
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            {% endif %}
                            {% for f in form if f.widget.input_type == 'hidden' %}
                                {{ f }}
                            {% endfor %}
                        {% endif %}

                        {% if form_opts and form_opts.form_rules %}
                            {% for r in form_opts.form_rules %}
                            {{ r(form, form_opts=form_opts) }}
                            {% endfor %}
                        {% else %}
                            {% for f in form if f.widget.input_type != 'hidden' %}
                                {% if form_opts %}
                                    {% set kwargs = form_opts.widget_args.get(f.short_name, {}) %}
                                {% else %}
                                    {% set kwargs = {} %}
                                {% endif %}
                                {% set direct_error = h.is_field_error(f.errors) %}
                                <div class="form-group{{ ' has-error' if direct_error else '' }}">
                                    <label for="{{ f.id }}" class="col-md-2 control-label">{{ f.label.text }}
                                        {% if h.is_required_form_field(f) %}
                                        <strong style="color: red">&#42;</strong>
                                        {%- else -%}
                                        &nbsp;
                                        {%- endif %}
                                    </label>
                                    <div class="{{ kwargs.get('column_class', 'col-md-5') }}">
                                        {% set _dummy = kwargs.setdefault('class', 'form-control') %}
                                        {{ f(**kwargs)|safe }}
                                        {% if f.description %}
                                        <p class="help-block">{{ f.description|safe }}</p>
                                        {% endif %}
                                        {% if direct_error %}
                                        <ul class="help-block input-errors">
                                            {% for e in f.errors if e is string %}
                                            <li>{{ e }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                    {% if caller %}
                                    {{ caller(form, f, direct_error, kwargs) }}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        {% endif %}

                      <div class="form-buttons">
                        {{ lib.render_form_buttons(return_url, extra()) }}
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

smbrewing/mgmt/templates/admin_edit.html
{% extends 'mgmt_layout.html' %}
{% import 'admin/lib.html' as lib with context %}
{% from 'admin/lib.html' import extra with context %} {# backward compatible #}

{% block css %}
{{ lib.form_css() }}
{% endblock %}

{% block sidebar %}
{% include "admin_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2 id="brand">Edit {{ admin_view.name|capitalize }}</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>

                    <form action="{{ action or '' }}" method="POST" role="form" class="form-horizontal form-label-left">
                        {% if form.hidden_tag is defined %}
                            {{ form.hidden_tag() }}
                        {% else %}
                            {% if csrf_token %}
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            {% endif %}
                            {% for f in form if f.widget.input_type == 'hidden' %}
                                {{ f }}
                            {% endfor %}
                        {% endif %}

                        {% if form_opts and form_opts.form_rules %}
                            {% for r in form_opts.form_rules %}
                            {{ r(form, form_opts=form_opts) }}
                            {% endfor %}
                        {% else %}
                            {% for f in form if f.widget.input_type != 'hidden' %}
                                {% if form_opts %}
                                    {% set kwargs = form_opts.widget_args.get(f.short_name, {}) %}
                                {% else %}
                                    {% set kwargs = {} %}
                                {% endif %}
                                {% set direct_error = h.is_field_error(f.errors) %}
                                <div class="form-group{{ ' has-error' if direct_error else '' }}">
                                    <label for="{{ f.id }}" class="col-md-2 control-label">{{ f.label.text }}
                                        {% if h.is_required_form_field(f) %}
                                        <strong style="color: red">&#42;</strong>
                                        {%- else -%}
                                        &nbsp;
                                        {%- endif %}
                                    </label>
                                    <div class="{{ kwargs.get('column_class', 'col-md-5') }}">
                                        {% set _dummy = kwargs.setdefault('class', 'form-control') %}
                                        {{ f(**kwargs)|safe }}
                                        {% if f.description %}
                                        <p class="help-block">{{ f.description|safe }}</p>
                                        {% endif %}
                                        {% if direct_error %}
                                        <ul class="help-block input-errors">
                                            {% for e in f.errors if e is string %}
                                            <li>{{ e }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                    {% if caller %}
                                    {{ caller(form, f, direct_error, kwargs) }}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        {% endif %}

                      <div class="form-buttons">
                        {{ lib.render_form_buttons(return_url, extra()) }}
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

smbrewing/mgmt/templates/admin_sidebar.html
{% import 'admin/layout.html' as layout with context -%}

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="" class="site_title"><i class="fa fa-beer"></i> <span>SMB Database</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{ asset_url_for('img/mugicon.png') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ current_user.full_name }}</h2>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                {% set menu_root = admin_view.admin.menu() %}

                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Navigation <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url_for('public.home') }}">Public Site</a></li>
                            <li><a href="{{ url_for('mgmt.index') }}">Management Dashboard</a></li>
                            <li><a href="#">Brewery Dashboard</a></li>
                            <li><a href="#">API Dashboard</a></li>
                            <li><a href="{{ url_for('useradmin.index_view') }}">Admin Dashboard</a></li>
                        </ul>
                    </li>
                    {%- for item in menu_root if item.name != 'Home' %}
                        {%- if item.is_category() -%}
                            {% set children = item.get_children() %}
                            {%- if children %}
                                {% set class_name = item.get_class_name() %}
                                {%- if item.is_active(admin_view) %}
                                    <li class="active dropdown">
                                {% else -%}
                                    <li>
                                {%- endif %}
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
                                          {% if item.class_name %}<span class="{{ item.class_name }}"></span> {% endif %}
                                          {% if 'User' in item.name %}
                                          <i class="fa fa-user"></i> {{ item.name }} <span class="fa fa-chevron-down"></span>
                                          {% elif 'Inventory' in item.name %}
                                          <i class="fa fa-database"></i> {{ item.name }} <span class="fa fa-chevron-down"></span>
                                          {% else %}
                                          <i class="fa fa-sort-desc"></i> {{ item.name }} <span class="fa fa-chevron-down"></span>
                                          {% endif %}
                                        </a>
                                        <ul class="nav child_menu">
                                            {%- for child in children -%}
                                            {% set class_name = child.get_class_name() %}
                                            {%- if child.is_active(admin_view) %}
                                            <li class="active{% if class_name %} {{class_name}}{% endif %}">
                                                {% else %}
                                                <li{% if class_name %} class="{{class_name}}"{% endif %}>
                                                {%- endif %}
                                                <a href="{{ child.get_url() }}"{% if child.target %} target="{{ child.target }}"{% endif %}>{{ child.name }}</a>
                                            </li>
                                            {%- endfor %}
                                        </ul>
                                    </li>
                            {% endif %}
                        {% else %}
                            {%- if item.is_accessible() and item.is_visible() -%}
                            {% set class_name = item.get_class_name() %}
                            {%- if item.is_active(admin_view) %}
                            <li class="{% if class_name %} {{class_name}}{% endif %}">
                                {%- else %}
                                <li{% if class_name %} class="{{class_name}}"{% endif %}>
                                {%- endif %}
                                <a href="{{ item.get_url() }}"{% if item.target %} target="{{ item.target }}"{% endif %}>{{ item.name }}</a>
                            </li>
                            {%- endif -%}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
                <a data-toggle="tooltip" data-placement="top" title="Settings">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Lock">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                </a>
            </div>
            <!-- /menu footer buttons -->
        </div>
    </div>

smbrewing/mgmt/templates/mgmt_blog_archive.html
{% extends "mgmt_layout.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="col-md-6 col-sm-4 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Blog Posts</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="dashboard-widget-content">
                <ul class="list-unstyled timeline widget">
                    {% for post in posts %}
                    <li>
                        <div class="block">
                            <div class="block_content">
                                <h2 class="title">
                                    <a>{{ post.title }}</a>
                                </h2>
                                <div class="byline">
                                    <span>13 hours ago</span> by <a>{{ post.user.full_name }}</a>
                                </div>
                                <p class="excerpt">{{ post.content[:82] }}</p>
                                <p><b>Published: </b>{{ post.published }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                    <li>
                        <div class="block">
                            <div class="block_content">
                                <h2 class="title">
                                    <a>Who Needs Sundance When You’ve Got&nbsp;Crowdfunding?</a>
                                </h2>
                                <div class="byline">
                                    <span>13 hours ago</span> by <a>Jane Smith</a>
                                </div>
                                <p class="excerpt">Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that could fund your project, and if the buyers liked your flick, they’d pay to Fast-forward and… <a>Read&nbsp;More</a>
                                </p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

smbrewing/mgmt/templates/mgmt_calendar.html
{% extends "mgmt_layout.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Management Dashboard</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Calendar Events <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=opfsh94bai0vdj4ldu6t16hbic%40group.calendar.google.com&amp;color=%23875509&amp;ctz=America%2FNew_York" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

smbrewing/mgmt/templates/mgmt_footer.html
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

smbrewing/mgmt/templates/mgmt_sidebar.html
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-beer"></i> <span>SMB</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{ asset_url_for('img/mugicon.png') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ current_user.full_name }}</h2>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Navigation</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url_for('public.home') }}">Public Site</a></li>
                            <li><a href="{{ url_for('mgmt.index') }}">Management Dashboard</a></li>
                            <li><a href="{{ url_for('brewery.index') }}">Brewery Dashboard</a></li>
                            <li><a href="#">API Dashboard</a></li>
                            <li><a href="{{ url_for('useradmin.index_view') }}">Admin Dashboard</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-file-text"></i> Blog <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url_for('mgmt.new_post') }}">Create Post</a></li>
                            <li><a href="{{ url_for('mgmt.blog_archive') }}">Archive</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-calendar"></i> Meetings <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url_for('mgmt.calendar') }}">Calendar</a></li>
                            <li><a href="{{ url_for('mgmt.minutes') }}">Minutes</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-history"></i> Activity <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="general_elements.html">Overview</a></li>
                            <li><a href="media_gallery.html">Time Spent</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-usd"></i> Accounting <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="tables.html">Tables</a></li>
                            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
                <a data-toggle="tooltip" data-placement="top" title="Settings">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Lock">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                </a>
            </div>
            <!-- /menu footer buttons -->
        </div>
    </div>