smbrewing/brewery/__init__.py
from . import views

smbrewing/brewery/views.py
# -*- coding: utf-8 -*-
"""Brewery views."""
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, current_app
from flask_login import current_user

from smbrewing.user.models import User
from smbrewing.blog.models import Post, Category
from smbrewing.beers.models import BeerRecipe, Beer, BeerStyle
from smbrewing.inventory.models import Hop, Fermentable, Yeast, Additive

blueprint = Blueprint('brewery', __name__, static_folder='./static',
                      subdomain='brewery',
                      template_folder='./templates')

@blueprint.route('/')
def index():

    return render_template('brewery_index.html')

@blueprint.route('/recipes')
def recipes():

    recipes = BeerRecipe.query.all()
    return render_template('brewery_recipes.html', recipes=recipes)

@blueprint.route('/beers')
def beers():

    beers = Beer.query.all()
    return render_template('brewery_beers.html', beers=beers)

@blueprint.route('/recipe/new')
def newrecipe():

    styles = BeerStyle.query.all()
    hops = Hop.query.all()
    fermentables = Fermentable.query.all()
    yeasts = Yeast.query.all()
    additives = Additive.query.all()
    return render_template('brewery_newrecipe.html', styles=styles,
                           hops=hops, fermentables=fermentables,
                           yeasts=yeasts, additives=additives)

smbrewing/brewery/templates/brewery_beers.html
{% extends "brewery_layout.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Beer</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Beer List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <p>Simple table with project listing with progress and editing options</p>

                    <!-- start project list -->
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 1%">#</th>
                                <th style="width: 20%">Name</th>
                                <th>Description</th>
                                <th>IBU</th>
                                <th>ABV</th>
                                <th style="width: 20%">Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if beers|length > 0 %}
                            {% for beer in beers %}
                            <tr>
                                <td>#</td>
                                <td>
                                    <a>{{ beer.name }}</a>
                                    <br>
                                    <small>{{ beer.style }}</small>
                                </td>
                                <td>
                                    {{ beer.description }}
                                </td>
                                <td>
                                    {{ beer.ibu }}
                                    <br>
                                    <small>IBU</small>
                                </td>
                                <td>
                                    {{ beer.abv }}%
                                    <br>
                                    <small>ABV</small>
                                </td>
                                <td>
                                    <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                    <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                    <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}

                            {% endif %}
                        </tbody>
                    </table>
                    <!-- end project list -->

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

smbrewing/brewery/templates/brewery_footer.html
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

smbrewing/brewery/templates/brewery_index.html
{% extends "brewery_layout.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Brewery Dashboard</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row top_tiles">
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
                    <div class="count">179</div>
                    <h3>New Sign ups</h3>
                    <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon"><i class="fa fa-comments-o"></i></div>
                    <div class="count">179</div>
                    <h3>New Sign ups</h3>
                    <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon"><i class="fa fa-sort-amount-desc"></i></div>
                    <div class="count">179</div>
                    <h3>New Sign ups</h3>
                    <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon"><i class="fa fa-check-square-o"></i></div>
                    <div class="count">179</div>
                    <h3>New Sign ups</h3>
                    <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Plain Page</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        Add content to the page ...
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>To Do List <small>Sample tasks</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="">
                            <ul class="to_do">
                                <li>
                                    <p>
                                        <div class="icheckbox_flat-green" style="position: relative;">
                                            <input type="checkbox" class="flat" style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        </div> Schedule meeting with new client
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        <div class="icheckbox_flat-green" style="position: relative;">
                                            <input type="checkbox" class="flat" style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        </div> Schedule meeting with new client
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        <div class="icheckbox_flat-green" style="position: relative;">
                                            <input type="checkbox" class="flat" style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        </div> Schedule meeting with new client
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        <div class="icheckbox_flat-green" style="position: relative;">
                                            <input type="checkbox" class="flat" style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        </div> Schedule meeting with new client
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        <div class="icheckbox_flat-green" style="position: relative;">
                                            <input type="checkbox" class="flat" style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        </div> Schedule meeting with new client
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

smbrewing/brewery/templates/brewery_layout.html
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">

    <title>
SMB Brewery Dashboard
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="{{ asset_url_for('mgmt_css.css') }}">
    {% block css %}{% endblock %}
</head>
<body class="{% block body_class %}nav-md{% endblock %}">
    {% block body %}

    <div class="{% block content_class %}container body{% endblock content_class %}">
        <div class="main_container">
            {% block sidebar %}
            {% include "brewery_sidebar.html" %}
            {% endblock %}

            {% include "brewery_topnav.html" %}
            <!-- page content -->
            {% block content %} {% endblock %}
            <!-- /page content -->
            <!-- footer -->
            {% include "brewery_footer.html" %}
            <!-- /footer -->
        </div>
    </div>


    <script type="text/javascript" src="{{ asset_url_for('mgmt_js.js') }}"></script>

    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
</body>
</html>

smbrewing/brewery/templates/brewery_recipes.html
{% extends "brewery_layout.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Recipes</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Recipe List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <p>Simple table with project listing with progress and editing options</p>

                    <!-- start project list -->
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 1%">#</th>
                                <th style="width: 20%">Recipe Name</th>
                                <th>OG</th>
                                <th>FG</th>
                                <th>IBU</th>
                                <th>SRM</th>
                                <th>ABV</th>
                                <th style="width: 20%">Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if recipes|length > 0 %}
                            {% for recipe in recipes %}
                            <tr>
                                <td>#</td>
                                <td>
                                    <a>{{ recipe.name }}</a>
                                    <br>
                                    <small>{{ recipe.style_name }}</small>
                                </td>
                                <td>
                                    {{ recipe.target_og }}
                                    <br>
                                    <small>OG</small>
                                </td>
                                <td>
                                    {{ recipe.target_fg }}
                                    <br>
                                    <small>FG</small>
                                </td>
                                <td>
                                    {{ recipe.target_ibu }}
                                    <br>
                                    <small>IBU</small>
                                </td>
                                <td>
                                    {{ recipe.target_srm }}
                                    <br>
                                    <small>SRM</small>
                                </td>
                                <td>
                                    {{ recipe.target_abv }}
                                    <br>
                                    <small>ABV</small>
                                </td>
                                <td>
                                    <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                    <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                    <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}

                            {% endif %}
                        </tbody>
                    </table>
                    <!-- end project list -->

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

smbrewing/brewery/templates/brewery_sidebar.html
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-beer"></i> <span>SMB</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{ asset_url_for('img/mugicon.png') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ current_user.full_name }}</h2>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Navigation</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url_for('public.home') }}">Public Site</a></li>
                            <li><a href="{{ url_for('mgmt.index') }}">Management Dashboard</a></li>
                            <li><a href="{{ url_for('brewery.index') }}">Brewery Dashboard</a></li>
                            <li><a href="#">API Dashboard</a></li>
                            <li><a href="{{ url_for('useradmin.index_view') }}">Admin Dashboard</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{ url_for('brewery.recipes') }}"><i class="fa fa-file-text"></i> Recipes</a>
                    </li>

                    <li>
                        <a href="{{ url_for('brewery.newrecipe') }}"><i class="fa fa-beer"></i> New Recipe</a>
                    </li>
                    <li>
                        <a href="{{ url_for('brewery.beers') }}"><i class="fa fa-beer"></i> Beers</a>
                    </li>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
                <a data-toggle="tooltip" data-placement="top" title="Settings">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Lock">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                </a>
            </div>
            <!-- /menu footer buttons -->
        </div>
    </div>

smbrewing/brewery/templates/brewery_topnav.html
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="{{ asset_url_for('img/mugicon.png') }}" alt="">{{ current_user.full_name }}
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green"></span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image"><img src="{{ asset_url_for('img/mugicon.png') }}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="{{ asset_url_for('img/mugicon.png') }}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="{{ asset_url_for('img/mugicon.png') }}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="{{ asset_url_for('img/mugicon.png') }}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->